[package]
name = "shorterDB"
version = "0.1.1"
authors = [
    "K V Varun Krishnan <hello@vrn21.com>",
    "M Arjun Krishna <arjunkrishna7356@gmail.com>",
]
edition = "2021"
description = "A simple Key value store built using SkipLists, De-LSM arch, embeddable and grpc enabled."
license = "MIT OR Apache-2.0"

[lib]
name = "shorterdb"
path = "src/lib.rs"


[dependencies]
anyhow = "1.0.86"
bytes = "1.7.1"
clap = { version = "4.0", features = ["derive"] }
crossbeam-skiplist = "0.1.3"
log = "0.4"
thiserror = "1.0.63"
tonic = "0.11"
tonic-web = "0.11"
tokio = { version = "1", features = ["full"] }
prost = "0.12.3"
tower-http = { version = "0.3", features = ["cors"] }

[build-dependencies]
tonic-build = "0.11"

[[bin]]
name = "server"
path = "src/bin/server.rs"


[[bin]]
name = "repl"
path = "src/bin/repl.rs"
